# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Logbee < Formula
  desc "Process manager for Procfile-based apps, with live log-file output"
  homepage "https://github.com/neatnettech/logbee"
  version "1.2.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/neatnettech/logbee/releases/download/v1.2.0/logbee_1.2.0_darwin_amd64.tar.gz"
      sha256 "9eb3410551bd657ab7cc081fad5a0346034cc7cd8d17e7bcd8886e2baaea4143"

      define_method(:install) do
        bin.install "logbee"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/neatnettech/logbee/releases/download/v1.2.0/logbee_1.2.0_darwin_arm64.tar.gz"
      sha256 "eeb5a54a3e37aebfb573095b948637b91d1e6b06399266f93472874d66156bcc"

      define_method(:install) do
        bin.install "logbee"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/neatnettech/logbee/releases/download/v1.2.0/logbee_1.2.0_linux_amd64.tar.gz"
      sha256 "91106ab437f69a59db30572ccb216860a0da777b2a870fb444847784126f33b7"
      define_method(:install) do
        bin.install "logbee"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/neatnettech/logbee/releases/download/v1.2.0/logbee_1.2.0_linux_arm64.tar.gz"
      sha256 "e6b25919701b9fed918371ea55218a65fb3036625ec50d3af633f811843a667f"
      define_method(:install) do
        bin.install "logbee"
      end
    end
  end

  test do
    system "#{bin}/logbee", "--version"
  end
end
